jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# manifest gen for VISUALIZER
  - name: shipdemo-manifest-gke
    type: manifest
    steps:
      - IN: shipdemo-img-gke
      - IN: shipdemo-img-options-gke-test
      - TASK: managed
    flags:
      - gke-loadbalancer

  - name: node-gcr-deploy-gke-loadbalancer_runCI
    type: runCI
    steps:
      - OUT: shipdemo-img-gke

# TEST deployment to Google GKE
  - name: shipdemo-deploy-gke-test
    type: deploy
    steps:
      - IN: shipdemo-manifest-gke
      - IN: shipdemo-params-gke-test
      - IN: shipdemo-cluster-gke
      - TASK: managed
    flags:
      - gke-loadbalancer

# Create external loadBalancer entrypoint for test service
  - name: shipdemo-service-gke-test
    type: provision
    steps:
      - IN: shipdemo-service-test
      - IN: shipdemo-deploy-gke-test
      - TASK: managed
    flags:
      - gke-loadbalancer

